### ISSUE TITLE
npm install es-abstract@v1.18.1 failure

### ISSUE THREAD

**Issue by mingfuqin** [ljharb/es-abstract#131]
Hi,
Installing the latest version failed, v1.18.1 to 1.18.3.
Reverting back to 1.18.0 works.

Thanks.

```
21:15:49  npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
21:15:49  npm ERR! node v6.3.1
21:15:49  npm ERR! npm  v3.10.3
21:15:49  npm ERR! code EMISSINGARG
21:15:49  
21:15:49  npm ERR! typeerror Error: Missing required argument #1
21:15:49  npm ERR! typeerror     at andLogAndFinish (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)
21:15:49  npm ERR! typeerror     at fetchPackageMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:51:22)
21:15:49  npm ERR! typeerror     at resolveWithNewModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:12)
21:15:49  npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:516:7
21:15:49  npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
21:15:49  npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
21:15:49  npm ERR! typeerror     at addRequestedAndFinish (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:67:5)
21:15:49  npm ERR! typeerror     at returnAndAddMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:121:7)
21:15:49  npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:138:20)
21:15:49  npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
21:15:49  npm ERR! typeerror This is an error with npm itself. Please report this error at:
21:15:49  npm ERR! typeerror     <http://github.com/npm/npm/issues>

```

**Comment by ljharb** [comment]
Both node 6 and npm 3 are ancient and EOL. On node 6, you can run `npm install -g npm@6`.

Either way, this is a bug with npm and not with any particular package.
